name: GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          clean: false
      - name: Update
        run: |
          git rm index.*.css
          git rm index.*.js
          cp -r dist/index.html dist/index.*.css dist/index.*.js .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff-index --quiet HEAD || git commit --message "Update GH pages using commit $GITHUB_SHA"
          git push
